version: "3.4"

services:
  epubmanage:
    image: epubmanage
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    volumes:
      - .:/code
volumes:
  logvolume01: {}
